### PR TITLE
Add a dummy withSnapshot HOF with some tests

### PR DESCRIPTION
**Pull request by emilgoldsmith**
Hey @lingz, there is no real functionality here, but just wanted to check in with you concerning types. I think the best way here is just using the any casts I did, but since I consider you the type wizard I just wanted to get a second opinion, and see if maybe there is a clean way I missed?

I'll merge this when CI passes as I'm the only one working on it but please do give feedback even though it's merged if you suggest any changes I'll just do it in a different PR

### CODE REVIEW

**Review by lingz — COMMENTED** [review]
Looks great really

**Comment by lingz** [comment]
I'm just wondering if there is a way to really hook it in from side-effect point of view, like rewire imports. It's debatable but some people might not like putting this into their prod code.

**Comment by lingz** [comment]
Or maybe with a decorator it would be a bit easier to put into the code, plus with a decorator you could use a string argument to preserve it across refactors.

**Comment by emilgoldsmith** [comment]
I looked at the spec for decorators though, and it only works in classes right? So that would not allow it to be used in more functional programming, yeah?

**Comment by lingz** [comment]
ah ok yes you are right

**Pull request merged**
